### ISSUE TITLE
No gf

### ISSUE THREAD

**Issue by S34NtheGuy** [Harry282/FunnyMap#1]
#### Issue description

I saw an advertisement for this skyblock hacked client that **explicitly** stated that being good at skyblock dungeons would get me a gf. It has been at least 3 months grinding in dungeons with this client, but my gf is still missing? 

#### Steps to reproduce the issue

1.  Download this mod
2.  Grind for 5 months
3.  No girls :(

#### What's the expected result?

- I would get a girlfriend that would tailor to my every need, preferably a tall, asian, and black haired.

#### What's the actual result?

- I am still lonely and have been single for 30 years.

#### Additional details / screenshot

- ![Screenshot](https://upload.wikimedia.org/wikipedia/commons/6/6e/Kim_Jong-un_April_2019_%28cropped%29.jpg)
- Image of expected result

**Comment by Harry282** [comment]
cry about it + stay mad + get real + L + mald seethe cope harder + hoes mad + basic + skill issue + ratio + you fell off + the audacity + triggered + any askers + redpilled + get a life + ok and? + cringe + touch grass + donowalled + not based + your're (french) + not funny didn't laugh + you're + grammar issue + go outside + get good + reported + ad hominem + GG! + ur mom
