### ISSUE TITLE
Render Player Head Crash

### ISSUE THREAD

**Issue by JackTYM** [Harry282/FunnyMap#7]
Crashed while starting a dungeon.

[crash-2022-07-07_19.33.11-client.txt](https://github.com/Harry282/FunnyMap/files/9068460/crash-2022-07-07_19.33.11-client.txt)

Config if it helps

[rooms]
	room_secrets = 1
	room_names = 1
	color_text = false
	dark_undiscovered_rooms = true
	room_checkmarks = 1

[debug]
	force_skyblock = false

[map]

	[map.size]
		map_x = 195
		map_text_scale = 0.7
		map_y = 96
		player_heads_scale = 1.0
		map_size = 1.9

	[map.scanning]
		auto_scan = true
		chat_info = true

	[map.toggle]
		show_run_information = true
		map_enabled = true
		show_player_names = 1
		hide_in_boss = true

	[map.render]
		map_border_color = "255,0,0,0"
		border_thickness = 3.0
		map_background_color = "100,0,0,0"

[colors]
	darken_multiplier = 0.4
	room_opacity = 1.0

	[colors.doors]
		entrance_door = "255,20,133,0"
		opened_wither_door = "255,92,52,14"
		blood_door = "255,231,0,0"
		wither_door = "255,0,0,0"
		normal_door = "255,92,52,14"

	[colors.rooms]
		rare_room = "255,255,203,89"
		blood_room = "255,255,0,0"
		fairy_room = "255,224,0,255"
		entrance_room = "255,20,133,0"
		puzzle_room = "255,117,0,133"
		mimic_room = "255,186,66,52"
		normal_room = "255,107,58,17"
		trap_room = "255,216,127,51"
		miniboss_room = "255,254,223,0"

**Comment by LagPixelLOL** [comment]
you can edit the bytecode in class funnymap.features.dungeon.MapRender method renderPlayerHeads() to

DEFINE PRIVATE FINAL renderPlayerHeads()V
A:
LINE A 203
NEW java/util/ArrayList
DUP
GETSTATIC funnymap/features/dungeon/Dungeon.Companion Lfunnymap/features/dungeon/Dungeon$Companion;
INVOKEVIRTUAL funnymap/features/dungeon/Dungeon$Companion.getDungeonTeamates()Ljava/util/List;
INVOKESPECIAL java/util/ArrayList.<init>(Ljava/util/Collection;)V
ASTORE players
B:
LINE B 204
ALOAD players
INVOKEINTERFACE java/util/List.iterator()Ljava/util/Iterator;
ASTORE 1
C:
LINE C 205
ALOAD 1
INVOKEINTERFACE java/util/Iterator.hasNext()Z
IFEQ E
ALOAD 1
INVOKEINTERFACE java/util/Iterator.next()Ljava/lang/Object;
CHECKCAST funnymap/core/DungeonPlayer
ASTORE player
GETSTATIC funnymap/utils/RenderUtils.INSTANCE Lfunnymap/utils/RenderUtils;
ALOAD player
INVOKEVIRTUAL funnymap/utils/RenderUtils.drawPlayerHead(Lfunnymap/core/DungeonPlayer;)V
D:
LINE D 207
GOTO C
E:
RETURN
F:

**Comment by LagPixelLOL** [comment]
it will fix the issue
